### ISSUE TITLE
iOS  crash

### ISSUE THREAD

**Issue by williamHlw** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#10]
[<NSConcreteValue 0x2809818c0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key x.

**Comment by walterjgsp** [comment]
Hi @williamHlw, thanks for reaching us. To help us address this issue could you provide us with the Xcode version being used, the version of the reCAPTCHA SDK, the minimum iOS version of your app and how to reproduce?

**Comment by williamHlw** [comment]
Thanks for your reply.
XcodeVersion:14.1
reCAPTCHA SDK Version:18.0.0
minimum iOS version: ios 14

**Comment by walterjgsp** [comment]
Hi @williamHlw, what steps should I follow to reproduce this error? I was not able to reproduce this specific error with the current setup that you provided.

**Comment by williamHlw** [comment]
Yes，I'm running on m1 macbook pro,using Cocoapods.It was crashed when execute.

**Comment by walterjgsp** [comment]
Hi @williamHlw, thanks for all the information. Is it still crashing or was one time only? Can you try it with the version 18.0.2? 
 
You received this error running on a simulator or real device? What's the OS of the device/simulator running the the app with reCaptcha? If it's a simulator are you running on the Mac OS Ventura or a previous version?

**Comment by williamHlw** [comment]
It's still crashing with the version 18.0.2. 
I received this error running on a real device with iphone8，iOS15.7,Mac OS Ventura 13.0

**Comment by walterjgsp** [comment]
Hey @williamHlw, could you provide us with a small project that also presents this crash, please? Don't need to be your full app code but some small one with the way you're integration reCaptcha and it's raising the same exception so we can reproduce it from our side. A small repository on Github that we can access with this code would be of great help to us.

**Comment by mcorner** [comment]
@williamHlw we noticed you closed the issue.  Did you you find the source of the issue in your app?

**Comment by williamHlw** [comment]
Yes, my fault, 18.0.2 will only trigger breakpoints, but it will not crash, and it will not affect normal use.
