### ISSUE TITLE
Add retries to API to mitigate network error

### ISSUE THREAD

**Issue by mcorner** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#100]
The API for getClient will fail in conditions of no, or poor networking. The nature of the SDK is that it needs to be connected to initialize and retrieve a token from execute. 

Our current proposal is to create a new API that will not require networking during initialization, but will begin the process in the background. It will wait for a network connection and automatically retry if needed. 

When subsequently calling execute the new API will wait for this initialization to complete up to the timeout (or infinitely if specified) and return an error if initialization or token retrieval cannot be completed in time. 

We feel that this will be easier to use and relieve the burden of retries from the implementor. 

Suggestions are always welcome.

**Comment by romaCaldeira** [comment]
@mcorner 
Hello everyone, how is this going?

**Comment by mcorner** [comment]
We are in the process of releasing a stable version of 18.5.0 as we speak.  Shortly after that we will have an 18.6.0-beta01 that will contain the new API. Android will be first, within about three weeks.  Then iOS will follow shortly.  We look forward to your feedback and hope that you find this API easier to integrate.

**Comment by romaCaldeira** [comment]
thank you very much for the feedback

**Comment by romaCaldeira** [comment]
@mcorner
Hello everyone, how is this going?

**Comment by mcorner** [comment]
We are targeting next week, but no promises.

**Comment by lemaildemrick** [comment]
Hi ! 

This week ? ;-)

**Comment by mcorner** [comment]
Yes, just documentation refinements holding it up

**Comment by mcorner** [comment]
18.6.0-beta01 for Android is out now with the new API.  iOS will come later, feedback is very welcome

**Comment by mcorner** [comment]
Note that the docs aren't out yet, that should be tomorrow, but fetchClient is the new API and it is synchronous.  In the background it does initialization and retries if there is a network failure.  This makes everything much easier to use.  Can't wait to bring this to iOS as well.

**Comment by mcorner** [comment]
The docs went out last week, Kotlin only for this release.

**Comment by mcorner** [comment]
@romaCaldeira and @lemaildemrick did you get a chance to try the new API?

**Comment by richieshilton** [comment]
Hi @mcorner - are there any updates on this for iOS? Thanks!

**Comment by walterjgsp** [comment]
Hi @richieshilton, the iOS for this is in the works and we will have it available soon.

**Comment by guillaume-lp-shopopop** [comment]
Hello @mcorner,
I tested version 18.6.0-beta02 and the `fetchClient` method works fine.
