### ISSUE TITLE
Change site key

### ISSUE THREAD

**Issue by richieshilton** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#102]
**Describe the bug**

We have a demo app which can change which backend environment it is pointing to. We would like to use different site keys for each environment. Currently the SDK will throw an exception if we try to get a new client with a different site key to the one that was initially used. 
Is there any way to change site key after the first client is initialised? It doesn't currently seem possible - but I'm hoping there is a way around this. 

Thank you.

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [x] SPM (iOS)
* [ ] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version (e.g. 18.0.1):**

18.4.2

**To Reproduce**

- Call get client twice, with different site keys
- Exception

**Expected behavior**

We would like a new client with the new site key

**Comment by walterjgsp** [comment]
Hi @richieshilton, currently our design limits the system to a single key per runtime and doesn't have multi-tenant capabilities. This means once the first client is set up, changing the site key isn't possible as you pointed. We definitely understand the need for multiple keys and hope to add this feature down the road, but I can't offer a specific timeframe

**Comment by richieshilton** [comment]
Hey @walterjgsp - just wondering if there's any movement on this? Thanks!

**Comment by walterjgsp** [comment]
Hi @richieshilton, currently, there's no movement on allowing multiple site keys. While we're not actively working on implementing this feature right now, it's definitely something that remains under consideration for the future.

I understand this might be important for your workflow. Could you elaborate a bit on why using only one site key is not feasible for your specific use case?
