### ISSUE TITLE
An error occurs when Xcode 14.2 compiles RecaptchaEnterprise 18.5.0-beta02 version.

### ISSUE THREAD

**Issue by MeiLaoban** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#107]
* [ ] Cocoapods (iOS)
pod "RecaptchaEnterprise", "18.5.0-beta02"

**SDK Version **
RecaptchaEnterprise  18.5.0-beta02

**Screenshots**
<img width="1089" alt="截屏2024-05-11 11 03 35" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/42988757/06e41ecc-9e9c-4f5e-a3c5-c7e3b4a77908">

**Xcode version for iOS (please complete the following information):**
 - Version [Xcode 14.2]

**Comment by mcorner** [comment]
Upgrade to xcode 15.3
