### ISSUE TITLE
Unable to build the App with SDK 18.5.0 on iOS

### ISSUE THREAD

**Issue by nik6018** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#109]
**Describe the bug**

After integrating the updated SDK 18.5.0, the app fails to build with the following error:
```
ld: warning: Could not find or use auto-linked library 'swiftXPC': library 'swiftXPC' not found
ld: Undefined symbols:
  __swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_Recaptcha in RecaptchaEnterprise[arm64][6](h5A6qS67.swift.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**reCAPTCHA Site Key**

6Lcbz_woAAAAAITamqDUxsv3kMcsrJUXVTHeEj93

**Integration Method**

SPM (iOS)

**SDK Version (e.g. 18.0.1):**

18.5.0

**To Reproduce**

1. Go to Project > Package Dependencies
2. Change the SDK version to 18.5.0
3. Build the APP
4. It will fail with the above mentioned error

**Expected behavior**

App should build without any errors

**Screenshots**

<img width="808" alt="Screenshot 2024-05-24 at 4 22 38 PM" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/16150710/5059dd0b-388f-4a39-8a48-738b6e06b700">

**Xcode version for iOS (please complete the following information):**
 - Version [Xcode 15.2]

**Device (please complete the following information):**
 - Model: [iPhone 15 Pro Max]
 - OS: [iOS 17.2]
 - Simulator

**Comment by walterjgsp** [comment]
Thanks for the report @nik6018, could you try building with Xcode 15.3, please? Due to Apple recent changes for SDKs we needed to use Xcode 15.3 to build the SDK and in the newest version also changes how static xcframeworks are handled.

**Comment by nik6018** [comment]
Hi @walterjgsp I tried building it with Xcode 15.3 and it was successful, Client & Token were successfully generated. 
Thanks for the response.
