### ISSUE TITLE
Getting error `Undefined symbols` - after updating to 18.5.0

### ISSUE THREAD

**Issue by michalsrutek** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#111]
**Describe the bug**

We're using CocoaPods to install `recaptcha-enterprise`.

After trying to update to `18.5.0` (also tried `18.5.1`), we're getting the following errors

```
⚠️  ld: Could not find or use auto-linked library 'swiftXPC': library 'swiftXPC' not found
⚠️  ld: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found

❌  ld: Undefined symbols:
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The build works just fine on `18.4.0`. Has something been changed that would cause this behavior? 🤔 

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [ ] SPM (iOS)
* [x] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version**

`18.5.0`

**To Reproduce**

1. Update to 18.5.0
2. Build the app with recaptcha dependency.
3. Get the linker error.

**Expected behavior**

Build successful.

**Xcode version**
 - Version 15.2.0

**Comment by mcorner** [comment]
Duplicate of #109   Upgrade XCode

**Comment by michalsrutek** [comment]
@mcorner thanks for the quick reply. Looks like this was the issue. Closing.
