### ISSUE TITLE
iOS | React native recaptcha enterprise Upgrade new version above > 18.2.2 have  issues in building

### ISSUE THREAD

**Issue by chirag-blueed** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#112]
**Describe the bug**

Not able to run the Xcode iOS build with the latest version of RN captcha enterprise 
<img width="747" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/144208553/841c28ae-e9b8-4561-9bb8-4c2859fa7c79">

**reCAPTCHA Site Key**

NA,  with this issue context

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

https://github.com/GoogleCloudPlatform/recaptcha-enterprise-react-native

**SDK Version (e.g. 18.0.1):**
18.4.4

Just install the new version and try to run the iOS build from Xcode facing the errors i attached in the ScreenShot

**Expected behavior**
With the new version of RN captcha iOS should work fine
**Screenshots**
<img width="747" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/144208553/5e92912b-3151-4112-a492-c357cbd43689">

**Xcode version for iOS (please complete the following information):**
 - Version 15.4 (15F31d)

**Device (please complete the following information):**
 real Device

**Additional context**

**Comment by chirag-blueed** [comment]
I need urgent help on this, Thanks

**Comment by mcorner** [comment]
Use 18.5.1 to make it easier for us to tell what is happening. 

Did you run pod install in the iOS directory?

Make sure you are using xCode 15.3 or above.

**Comment by chirag-blueed** [comment]
Hi @mcorner  I have tried the latest one too 18.5.1, The iOS pod install was done for both the version 18.5.1/18.4.0

but for specific 18.5.1, faced below error

```
ld: Undefined symbols:
  __swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_Recaptcha in RecaptchaEnterprise[6](h5A6qS67.swift.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Yes the latest version of Xcode 

<img width="449" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/144208553/c7962c74-0e19-476e-a59d-8a7c30790d00">

Can you please help with one of the version's fix?
Thanks

**Comment by walterjgsp** [comment]
@chirag-blueed, are you able to try with Xcode 15.3? There was a bug on Xcode 15.3 that we needed to work around for the SDK to work on it and maybe the new Xcode 15.4 solved the bug but made our SDK unusable.

Clearing the cache maybe help as if you see the code here https://github.com/GoogleCloudPlatform/recaptcha-enterprise-react-native/blob/main/ios/RecaptchaEnterpriseReactNative-Bridging-Header.h we do not have the `import <RecaptchaEnterprise/RecaptchaEnterprise.h>` anymore in the newest version. 

Since you're coming from an old version try to deintegrate the pod and install it again: 

```
pod deintegrate && pod install
```

**Comment by chirag-blueed** [comment]
@walterjgsp I attempted to remove the Pods and reinstall, but I still encountered the errors.

With version 18.5.1, the two errors still exist. I made sure to remove the pods and clear the cache.
Can you please check 

<img width="1633" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/144208553/c0c79371-c90d-44d7-9bea-c34a9f9c9ba3">

**Comment by walterjgsp** [comment]
We created a PR to check running the tests with Xcode 15.4 (https://github.com/GoogleCloudPlatform/recaptcha-enterprise-react-native/pull/37) and it seems that it should work without a problem. Could you check all the installed pods and see if the `RecaptchaInterop` is there, please?

If possible can you create a small reproduction project and share with us? That way we can reproduce from our side and iterate faster.

**Comment by chirag-blueed** [comment]
<img width="356" alt="Pasted_Image_05_06_24__5_06 PM" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/144208553/c91b8237-5f44-428d-943c-34527ebc1bd0">

Both exist in the Pods, but not sure why i am getting the same error again and again

**Comment by walterjgsp** [comment]
What's the cocoapods version that's being used?

**Comment by chirag-blueed** [comment]
cocoapods-1.15.2

**Comment by walterjgsp** [comment]
And what's the result for `xcode-select --print-path`? Do you have a small reproduction that we can iterate over from our side?

**Comment by chirag-blueed** [comment]
For now, I'm on Xcode 15.4,  it's difficult to switch to the Xcode version immediately 

```
xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
```
I need create a React native demo project and then need to re-create the problem, and it may take a time

**Comment by mcorner** [comment]
Sorry, do this to get the version: 
`/usr/bin/xcodebuild -version`

Also, there is a sample app in the repository you can build and try.

**Comment by chirag-blueed** [comment]
```
/usr/bin/xcodebuild -version

Xcode 15.4
Build version 15F31d
```

**Comment by chirag-blueed** [comment]
@walterjgsp and @mcorner As per your suggestion, I tried using Xcode Version 15.3 and encountered a similar problem. This issue is reproducible with the demo React Native project. Could you try it out?

Note:The version 18.2.2 is working fine without any issues!

<img width="1387" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/144208553/765421a5-989a-4bc7-abe7-201284678666">

**Comment by chirag-blueed** [comment]
Hey team, I urgently need your assistance. We are about to release our product, and Android requires the latest version of the Captcha SDK. We have received a warning in the Google Play Store, and unfortunately, due to an issue with iOS, we are unable to proceed further. Any quick help with this matter would be greatly appreciated! Thank you.

**Comment by walterjgsp** [comment]
> This issue is reproducible with the demo React Native project

That's the project that I'm using and it's working without issue in my machine. Also in Github Actions we use the sample app for the integration tests and it's passing.

> The version 18.2.2 is working fine without any issues!

Since you're jumping from a old version the cache could be a really big issue and `pod deintegrate` could be not enough to solve. Can you try to:

1. Clean the Xcode build cache.
2. Do `pod deintegrate` and close the project. 
3. Remove the `Podfile.lock` if is there.
4. Delete the `node_mudules` folder
5. Clean the derived data:

```bash
rm -rf ~/Library/Developer/Xcode/DerivedData/*
```

6. Reinstall everything again `npm install` and `pod install`

**Comment by chirag-blueed** [comment]
Hi @walterjgsp 
Before reporting this issue, I made sure to perform the steps you suggested in the previous comment. I tried everything by clearing caches and reverting back to old and new versions. After clearing the caches and installing fresh modules, I am still facing the issue.
Have you tried the demo React native App?

**Comment by walterjgsp** [comment]
> Have you tried the demo React native App?

Just to confirm, is this app that you're talking about? https://github.com/GoogleCloudPlatform/recaptcha-enterprise-react-native/tree/main/example 

We execute manual tests and automated tests on this app before each release for RN.

**Comment by chirag-blueed** [comment]
No, I am talking about creating a new RN app follow this: https://reactnative.dev/docs/getting-started-without-a-framework 
and after installing the latest Captcha packages you may encounter the errors I posted during the compilation of the iOS  app in Xcode

**Comment by mcorner** [comment]
Could you post your project in GitHub and share it with us?

**Comment by chirag-blueed** [comment]
@mcorner and @walterjgsp  is use_frameworks! :linkage => :static is required to add in the Pod file?, because after adding it i am facing other Pod-related errors, such as RNFirebase, e.t. c

**Comment by mcorner** [comment]
Yes, static linking is required. Firebase also uses static linking.

**Comment by chirag-blueed** [comment]
`$RNFirebaseAsStaticFramework = true` is already added but then it gives, other module map errors

**Comment by mcorner** [comment]
At this stage we are pretty confident that there isn't an issue in reCAPTCHA. We can't really provide support beyond the library itself. To go any further we need a minimal reproduction in a repository.

**Comment by sanaf1333** [comment]
@chirag-blueed were you able to resolve the issue? I am facing a similar error, when I run the app I get the error that "Error: The package '@google-cloud/recaptcha-enterprise-react-native' doesn't seem to be linked." even though I have done pod install multiple times after removing pods, podfile.lock, node_modules. I have also added these in podfile
use_frameworks! :linkage => :static
flipper_config = FlipperConfiguration.disabled

When I build in xcode I get these errors
<img width="326" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/101400000/20a465b7-1064-4cb8-a71c-0949dc87facc">

**Comment by mcorner** [comment]
If you have a minimal reproduction in a repository, we can take a look.  Also, try out the sample in the repository.

**Comment by chirag-blueed** [comment]
> @chirag-blueed @mcorner were you able to resolve the issue? I am facing a similar error, when I run the app I get the error that "Error: The package '@google-cloud/recaptcha-enterprise-react-native' doesn't seem to be linked." even though I have done pod install multiple times after removing pods, podfile.lock, node_modules. It works on android but not on IOS. I have also added these in podfile
> 
> ```
> use_frameworks! :linkage => :static
> flipper_config = FlipperConfiguration.disabled
> ```
> 
> When I build in xcode I get these errors <img alt="image" width="326" src="https://private-user-images.githubusercontent.com/101400000/338745424-20a465b7-1064-4cb8-a71c-0949dc87facc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjg1NDQsIm5iZiI6MTcxODE2ODI0NCwicGF0aCI6Ii8xMDE0MDAwMDAvMzM4NzQ1NDI0LTIwYTQ2NWI3LTEwNjQtNGNiOC1hNzFjLTA5NDlkYzg3ZmFjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwNDU3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2Y5MTVjOWQ2YmM3YzQzNDNjODcyNmE4NDk1MWJiNzI2MTdjZjE4OGIxOTBiNTgxYjJhZDU2ZTY5ZDYwZDY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hPw6HXSEeoxJvs2rp2OnI5eBjBF1MQWhTjUXDEp54GQ">

Hi @sanaf1333 3 You're right, I've been facing the same issue since the beginning. @mcorner and @walterjgsp Can you please take a look at this again? I'm pretty sure this is affecting everyone who is using the package for React Native.

**Comment by mcorner** [comment]
It definitely doesn't affect everyone. We also have automated tests you can see where it doesn't happen either. We cannot reproduce your issue and due to the complexity of react native we will need you to provide a reproduction in a GitHub repo for us to look at.

**Comment by mcorner** [comment]
Closing this due to a lack of response.
