### ISSUE TITLE
Improve bad score

### ISSUE THREAD

**Issue by jlajara-quadient** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#115]
Hello ! I'm asking here because I can't seem to find information on the subject.
What are the ways to improve a bad score on reCaptcha entreprise on mobile devices ?
Since we can't present visual challenges what are the options ?
Because I'm implementing it on my mobile app and I would like to at least guide the user to improve his score in case his score is low.
Thank you.

**Comment by mcorner** [comment]
At the moment there are no options built into the SDK.  There are examples in the repository for implementing visual challenges in a webview. Other options include MFA (email, SMS etc) or soft-blocking of requests through limited privileges.

**Comment by walterjgsp** [comment]
Thanks for reaching out @jlajara-quadient! I hope that @mcorner answers about the visual challenges helps you. 

> What are the ways to improve a bad score on reCaptcha entreprise on mobile devices ?

For score related questions please refer to the regular support channels https://cloud.google.com/recaptcha-enterprise/docs/support

**Comment by walterjgsp** [comment]
Closing this bug due to it being idle.
