### ISSUE TITLE
No network found on device exception

### ISSUE THREAD

**Issue by aligokdemir** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#117]
**Describe the bug**

We're using the Recaptcha Enterprise SDK in our mobile application since May. It was working fine but after 18.5.1 update in your SDK, we started to receive com.google.android.recaptcha.RecaptchaException
No network found on device **com.google.android.recaptcha.RecaptchaException No network found on device** exception. We're an online first application and this is kinda makes no sense to receive this much No network found on device error. Can you help me understand the problem.

**reCAPTCHA Site Key**

6Ldr79EpAAAAAFasAqiUJJMZCZBb2pJLJoaNWq0h

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [ ] SPM (iOS)
* [ ] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [x] GMaven (Android)

**SDK Version:** 18.5.1

**To Reproduce**

We're using Initializer class that Google provides in the launch of the application.

```
    private fun initializeRecaptcha() {
        lifecycleOwner.lifecycleScope.launch {
            Recaptcha.getClient(application, apiKey)
                .onSuccess { client ->
                    recaptchaProvider.recaptchaClient = client
                }
                .onFailure { exception ->
                    ThrowableReporter.report(exception)
                }
        }
    }
```
Inside the method it is executing onFailure callback and reporting an exception in our Crashlytics log.

**Expected behavior**

Assign the SDK in onSuccess callback of the get client method.

**Screenshots**

<img width="800" alt="image" src="https://github.com/user-attachments/assets/a08a6810-4427-4ebd-ab6d-290789be6d57">

**Device (please complete the following information):**

<img width="617" alt="image" src="https://github.com/user-attachments/assets/743adafa-a910-42f8-9ba5-5696d74cb16d">

**Comment by walterjgsp** [comment]
Hi @aligokdemir, thanks for reaching out to us. 

I do have some follow up questions that could help us diagnose what's happening. What's the ratio that are you seeing this exception? If you can share,where is the method `initializeRecaptcha` being called in your flow? Do you have any full stack trace that can share with us to do some more investigation from our side?

What could be happen is that the exact moment the `init` API is called to retrieve the reCaptcha client there's no internet connection and the client can't be initialized, the SDK will check for Network availability and return this exception. Some time pass and this connection appears latter, but the exception was already returned and the retrieval of the client never retried. The difference is that in the previous versions of the SDK before 18.5.1 this was being labeled as internal error. 

Some other developers reach out to us for the same reason. In those cases what helped to decrease this exception ratio was to wrap the `init` call around a retry with exponential backoff. We are in the works to make the retry implementation built-in and the new beta version of SDK (18.6.0-beta01) already have a new API called `fetchClient` that you can already try. If possible please try it out this API, and please fell free to give us feedback you have.

**Comment by aligokdemir** [comment]
Hello @walterjgsp, thanks for the quick response. Let me share with you the details. I'm calling the `initializeRecaptcha` method inside the Initializer class provided by Google to init some of the SDK or flows that will be used during the app's lifecycle.
```
import androidx.startup.Initializer

class RecaptchaInitializer : Initializer<Unit> {

    @EarlyEntryPoint
    @InstallIn(SingletonComponent::class)
    interface RecaptchaInitializerEntryPoint {

        fun inject(initializer: RecaptchaInitializer)
    }

    @Inject
    @ApplicationScope
    lateinit var lifecycleOwner: LifecycleOwner

    @Inject
    lateinit var application: Application

    @Inject
    lateinit var recaptchaProvider: RecaptchaProviderImpl

    @Inject
    lateinit var localConfigUseCase: GetLocalConfigUseCase

    override fun create(context: Context) {
        EarlyEntryPoints
            .get(context.applicationContext, RecaptchaInitializerEntryPoint::class.java)
            .inject(this)

        initializeRecaptcha()
    }

    private fun initializeRecaptcha() {
        val apiKey = localConfigUseCase.getBuildVariantConfig(KEY_RECAPTCHA_CONFIG)

        lifecycleOwner.lifecycleScope.launch {
            Recaptcha.getClient(application, apiKey)
                .onSuccess { client ->
                    recaptchaProvider.recaptchaClient = client
                }
                .onFailure { exception ->
                    ThrowableReporter.report(exception)
                }
        }
    }

    override fun dependencies(): List<Class<out Initializer<*>>> = listOf(ThrowableReporterInitializer::class.java)

    private companion object {
        const val KEY_RECAPTCHA_CONFIG = "RecaptchaKey"
    }
}
```

What's weird to me is that if it were a case for lack of internet connection then I wouldn't expect this high number of same exceptions. We received around a million non fatal logs for this issue. Retrying the initialization may solve the problem but what is actually causing this exception to occur I want to learn that actually. Another weird thing is that, Crashlytics shows that app is in the background %100 in these exceptions. 

In your recommendation if I use 18.6.0-beta01 version, do I need to call the init method only once? Or should I implement the retry mechanism again?

**Comment by aligokdemir** [comment]
let me try the retry mechanism and get back if it doesn't work. thanks for your interest and fast responses 🙏

**Comment by walterjgsp** [comment]
Thanks a lot @aligokdemir, let me know the results you see by using the new API and if you have questions about integrating with it.

**Comment by aligokdemir** [comment]
hi again @walterjgsp 

In our latest version, we implemented the retry mechanism ourselves instead of migrating to a beta version library and our implementation is just like below. although we did the retry mechanism implementation, we still get the no network found on device error. in the implementation, I'm trying to initialize the SDK for 4 times with exponential backoff, which lasts around 20 seconds, but still we get this error. it kinda confused me. can you check please 🤔 

``` kotlin
import androidx.startup.Initializer

class RecaptchaInitializer : Initializer<Unit> {

    @EarlyEntryPoint
    @InstallIn(SingletonComponent::class)
    interface RecaptchaInitializerEntryPoint {

        fun inject(initializer: RecaptchaInitializer)
    }

    @Inject
    @ApplicationScope
    lateinit var lifecycleOwner: LifecycleOwner

    @Inject
    lateinit var application: Application

    @Inject
    lateinit var recaptchaProvider: RecaptchaProviderImpl

    @Inject
    lateinit var localConfigUseCase: GetLocalConfigUseCase

    override fun create(context: Context) {
        EarlyEntryPoints
            .get(context.applicationContext, RecaptchaInitializerEntryPoint::class.java)
            .inject(this)

        initializeRecaptcha()
    }

    private fun initializeRecaptcha() {
        val apiKey = localConfigUseCase.getBuildVariantConfig(KEY_RECAPTCHA_CONFIG)

        lifecycleOwner.lifecycleScope.launch {
            var currentDelay = KEY_RECAPTCHA_INITIAL_DELAY
            var attempts = 0
            while (attempts < KEY_RECAPTCHA_MAX_RETRY_COUNT) {
                Recaptcha.getClient(application, apiKey)
                    .onSuccess { client ->
                        recaptchaProvider.recaptchaClient = client
                        return@launch
                    }
                    .onFailure { exception ->
                        attempts++
                        if (attempts >= KEY_RECAPTCHA_MAX_RETRY_COUNT) {
                            ThrowableReporter.report(exception)
                        } else {
                            delay(currentDelay)
                            currentDelay = (currentDelay * KEY_RECAPTCHA_BACKOFF_FACTOR).toLong()
                        }
                    }
            }
        }
    }

    override fun dependencies(): List<Class<out Initializer<*>>> = listOf(ThrowableReporterInitializer::class.java)

    private companion object {
        const val KEY_RECAPTCHA_CONFIG = "RecaptchaKey"
        const val KEY_RECAPTCHA_MAX_RETRY_COUNT = 4
        const val KEY_RECAPTCHA_INITIAL_DELAY = 1000L
        const val KEY_RECAPTCHA_BACKOFF_FACTOR = 2.0
    }
}
```

**Comment by walterjgsp** [comment]
Thanks for the fast feedback @aligokdemir.

Looking at the code the implementation looks correct to me. I have some follow up questions following that. 

1. Do you have idea of what is the ratio that you're seeing `NoNetworkException`? Even if you're an online first application I imagine that could exist the use case that the user started the app without network and changed in the middle of it. Since the `Initializer` will trigger before the application fully start, from what I understood in the documentation, could be that when you call `getClient` there's no network at all. 

1. Can you try to check for the network availability when you're calling the `getClient` API? Following this link https://stackoverflow.com/a/4239019 is an example on how to do it. I don't discard our code having some edge cases in detecting the network connection as the status of network availability can change really fast. That's the main reason why we first attempt to initialize the client from our end and only after it fail that we check for the network availability to decide what exception to return. In summary if you are seeing a `NoNetworkException` in previous versions that would be an `InternalException`.

1. Are you open to try using the `WorkManager` together with the `Initializer` as presented here https://developer.android.com/topic/libraries/app-startup#startup-initialize? Using the `WorkManager` you can create a constraint to execute the work of initializing reCaptcha of having network connection, some guidance can be found here https://developer.android.com/develop/background-work/background-tasks/persistent/getting-started/define-work and more directly here https://medium.com/coding-blocks/handling-offline-network-request-workmanager-to-the-rescue-613887cd3034

1. Is there a specific reason why you haven't tried the new API? The new API don't just add retries but also has bug improvements on the SDK. 

Please let me know how it works out. I will keep investigating from our side to see what can be done to improve the experience.

**Comment by aligokdemir** [comment]
1. this cannot be the case as we see this exception for 1.3 million users. I guess all of them won't open their internet connections in the middle of the execution of our app.
2. in previous versions I saw that we got InternalExceptions. what's weird about the connection issue is that I don't get this exception in debug packages and cannot repeat the scenario, but when we publish our application users face this. so even though I check network connection status, I'll always see connected on my side.
3. let me discuss this with my team and get back to you.
4. since the new API is beta I didn't want to migrate the application to this version. but if you think that version may solve the problem we can also try that.

**Comment by walterjgsp** [comment]
> so even though I check network connection status, I'll always see connected on my side.

I suggested this check to be added just to be sure that there's an internet connection the moment that `getClient` is called. Using the example of code you gave us would be something like:

```
private fun checkNetworkConnection(): Bool {
   ConnectivityManager connectivityManager 
          = (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
    NetworkInfo activeNetworkInfo = connectivityManager != null ? connectivityManager.getActiveNetworkInfo() : null;
    return activeNetworkInfo != null && activeNetworkInfo.isConnected(); 
}

private fun initializeRecaptcha() {
        val apiKey = localConfigUseCase.getBuildVariantConfig(KEY_RECAPTCHA_CONFIG)

        lifecycleOwner.lifecycleScope.launch {
            var currentDelay = KEY_RECAPTCHA_INITIAL_DELAY
            var attempts = 0
            while (attempts < KEY_RECAPTCHA_MAX_RETRY_COUNT) {
                if(!checkNetworkConnection()){
                    ThrowableReporter.report(SOME_EXCEPTION)
                }
                Recaptcha.getClient(application, apiKey)
                    .onSuccess { client ->
                        recaptchaProvider.recaptchaClient = client
                        return@launch
                    }
                    .onFailure { exception ->
                        attempts++
                        if (attempts >= KEY_RECAPTCHA_MAX_RETRY_COUNT) {
                            ThrowableReporter.report(exception)
                        } else {
                            delay(currentDelay)
                            currentDelay = (currentDelay * KEY_RECAPTCHA_BACKOFF_FACTOR).toLong()
                        }
                    }
            }
        }
    }
```

We already had before reports of the network connection not being established at the initial phases of the app start up but moving forward things were working as expected. I just want to confirm that in the `Initializer` component the network behavior is as expected. Can you try to call the `Recaptcha.getClient(application, apiKey)` outside of the `Initializer` component a little latter in the app flow? Just want to know what happens in this case.

> since the new API is beta I didn't want to migrate the application to this version. but if you think that version may solve the problem we can also try that.

Totally understandable, we are working fast to make this API out of beta as soon as possible. I will let you know when we do that.

**Comment by walterjgsp** [comment]
@aligokdemir, want to update you that we released the new version 18.6.0 that has built-in retries on the new API `fetchClient`. Let me know if using this API works for you.

**Comment by mcorner** [comment]
@aligokdemir  

Please let us know how the new SDK is doing when you get a chance.

**Comment by aligokdemir** [comment]
I lost my access to this github account and just got it back. I'll update the SDK to the latest version and let you know.

**Comment by phosphore** [comment]
We are on 18.7.0 and experiencing similar issues. Could it be cause by the Wi-Fi + Data connections being disabled by users at times, making these interfaces not available to the SDK?
