### ISSUE TITLE
High rates of internal error

### ISSUE THREAD

**Issue by gmichelan2** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#125]
**Describe the bug**

We integrated recaptcha in our application and we are getting the client when the user logins and when it buy or activates new packs.
However, we are experiencing a high rate of "internal errors" when reCAPTCHA attempts to retrieve the client.  

I'm not sure if the issue lies in the integration or the way we are using the library.

We created a specific module that is set up in the application. We pass the application context and then initialize a reCAPTCHA client instance inside a public object. This object is used to execute all token calls.

The issue is that most client instantiations are failing.

The exception is : 

 com.google.android.recaptcha.RecaptchaException: Internal Error

**reCAPTCHA Site Key**

I can email you with  this one but not publicly here

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [ ] SPM (iOS)
* [ ] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [ x] GMaven (Android)

We are using Android integration

**SDK Version (e.g. 18.0.1):**

18.5.1

**Screenshots**

This is the stack showed by loggly

![image](https://github.com/user-attachments/assets/a8e8a6e9-18c2-4754-aef8-a2789008ef38)

**Comment by walterjgsp** [comment]
Thanks for the report @gmichelan2! What's the ratio of InternalErrors that you're seeing? Could you also share your site key with us by answering this form? https://docs.google.com/forms/d/1_Q7w2DObo_x0mE6CUnl0EE4v_grfbDrt8Oy5QUd1Jaw/viewform?edit_requested=true&resourcekey=0-lgvDmnDD3HJWmoJWyIXj6g

If possible try to integrate with the version 18.6.0 of our SDK, this one is more reliable and has a new API that has built-in retries.
