### ISSUE TITLE
Undefined symbols on XCode 13: _objc_msgSend$stringWithUTF8String

### ISSUE THREAD

**Issue by mcorner** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#13]
**Describe the bug**

Can't archive using XCode 13

Internal bug reference: b/259435662

Undefined symbols for architecture arm64:
  "_objc_msgSend$stringWithUTF8String:", referenced from:
      +[tuTGkjsP voidEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      +[tuTGkjsP stringEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      +[tuTGkjsP booleanEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      +[tuTGkjsP charEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      +[tuTGkjsP intEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      +[tuTGkjsP shortEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      +[tuTGkjsP longlongEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      ...
  "_objc_msgSend$stringWithFormat:", referenced from:
      -[RecaptchaError description] in RecaptchaEnterprise(u844ZMu1.o)
      +[tuTGkjsP structureCGRectEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      +[tuTGkjsP structureCGSizeEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      +[tuTGkjsP structureCGPointEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      +[tuTGkjsP structureNSRangeEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      +[tuTGkjsP arrayEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      +[tuTGkjsP pointerEncoding] in RecaptchaEnterprise(wcUnAzvb.o)
      ...

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [ ] SPM
* [x] Cocoapods
* [ ] Direct Download

**SDK Version (e.g. 18.0.1):**
18.0.2
**To Reproduce**

Archive an app on Xcode 13

**Expected behavior**

Archive correctly 

**Xcode version (please complete the following information):**
XCode 13

**Device (please complete the following information):**
N/A

**Additional context**

**Comment by leopic** [comment]
I am seeing the same, this was after disabling Bitcode, which was the original cause of failure for us:

```
'/Users/runner/Library/Developer/Xcode/DerivedData/REDACTED-bpuvnwhwpexasfdaknjnhnbzhivj/Build/Intermediates.noindex/ArchiveIntermediates/REDACTED.debug/BuildProductsPath/Debug-iphoneos/RecaptchaEnterprise.a(obfuscated-RecaptchaAction.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/runner/Library/Developer/Xcode/DerivedData/REDACTED-bpuvnwhwpexasfdaknjnhnbzhivj/Build/Intermediates.noindex/ArchiveIntermediates/REDACTED.debug/BuildProductsPath/Debug-iphoneos/RecaptchaEnterprise.a' for architecture arm64
```

**Comment by mcorner** [comment]
18 had bitcode IIRC.  But Apple isn't accepting bitcode apps anymore so we had to turn it off.  As I said, we are looking at what can be done for XCode 13.  Probably the best option is recompiling the SDK with 13 while everyone catches up, but that has some other implications we have to work though.  14 should work fine.

**Comment by mcorner** [comment]
We are targeting a release of a fix this week (recompiling with XCode 13).

**Comment by mcorner** [comment]
18.0.3 and is compiled with XCode 13.  Let us know if this works (but note there is a scoring bug ATM: #16)

**Comment by mcorner** [comment]
Closing this as 18.0.3 should fix it.  Please open a new issue if not.

**Comment by mrchauhan2802** [comment]
I am having the same issue how can I resolve it ?
![Uploading Screenshot 2024-03-07 at 3.10.37 pm.png…]()

**Comment by mrchauhan2802** [comment]
I am having the same issue how can I resolve it ?
<img width="803" alt="Screenshot 2024-03-07 at 3 10 37 pm" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/39663213/2bbc911a-e9e3-454f-b67b-7cab27edb6dc">

**Comment by walterjgsp** [comment]
Hi @mrchauhan2802. To give you the most accurate troubleshooting, could you please open a new bug report? It'll help us understand your specific Xcode and SDK setup so we can find a solution.
