### ISSUE TITLE
After update score 0.3

### ISSUE THREAD

**Issue by SurglogsGithubUser** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#16]
**After update to 18.0.2 from 17.0.0, recaptcha always return score 0.3**

**Integration Method**

* [ ] SPM

**SDK Version: 18.0.2**

**To Reproduce**

1. Update recaptcha to 18.0.2
2. Execute action "login"
3. Send generated token to our server
4. Verify recaptcha
5. Got score only 0.3

**Expected behavior**

Get score at least 0.9, like on older version

**Screenshots**

**Xcode version (please complete the following information):**
 - Version [e.g. Xcode 14.1]

**Device (please complete the following information):**
 - Simulator and also Real device, current iOS16.1

**Comment by mcorner** [comment]
Thanks for the bug report, we are looking into it.

Internal bug reference: b/260560598

**Comment by mcorner** [comment]
We have identified the issue and fixed the issue internally.  We will have the fix in production on Dec 9.  (slight delay due to production release freezes around US holidays).

**Comment by SurglogsGithubUser** [comment]
Hi, when can I expect the fix?

**Comment by mcorner** [comment]
We believe we have addressed this issue in production.  Let us know if you experience continuing issues.

**Comment by SurglogsGithubUser** [comment]
So, this doesn't seem to be fixed in 18.0.3

**Comment by SurglogsGithubUser** [comment]
On simulator and also on real device.

**Comment by mcorner** [comment]
Ok, looking into it

**Comment by mcorner** [comment]
@SurglogsGithubUser We did some digging.  We are seeing some lower scores from your testing in comparison to others, though it isn't all 0.3, some are higher.  Is there anything happening with your devices out of the ordinary: network blocking, VPN, etc?

**Comment by MadalinaSpataru** [comment]
Hi, this is still an issue for us also on real device.

**Comment by mcorner** [comment]
Reopened.

@MadalinaSpataru @SurglogsGithubUser Can you try something for me?

1. in Xcode, add the App Attest capability to the app.  (Signing+Capabilities -> +Capability)
2. In the project's .entitlements file, set the App Attest environment to production (In the File Explorer find the .entitlements file and change development to production for App Attest)

**Comment by mcorner** [comment]
ATM, we think there is a second issue, will update.

**Comment by SurglogsGithubUser** [comment]
> 

Should I still try this?

**Comment by mcorner** [comment]
@SurglogsGithubUser For the long-term, yes you should do that.

We have a change rolling out this week (should complete by Fri) that will give much higher scores to your test devices.  Another change to further improve scoring will rollout the first or second week of Jan after the holidays.  Then expect further improvements on an ongoing basis.

**Comment by mcorner** [comment]
The change rolled out on the 23rd and addressed the issue.  More updates will rollout over the coming weeks to further improve scores.

**Comment by andrewjmeier** [comment]
Hi @mcorner I stumbled on this thread after having the same issues above and I believe adding App Attest will fix my problems (still some broader testing that I'd like to do). It would be great if you could update the CHANGELOG here https://cloud.google.com/recaptcha-enterprise/docs/release-notes with that information to make it easier for the next folks updating to find 😃  (I think 18.0.0 is the first version that requires it) 

Am I reading this correctly that App Attest is only needed for local development? 
<img width="832" alt="image" src="https://user-images.githubusercontent.com/3655258/216467186-6708f4d0-bc7b-4323-a552-3e596c8fd253.png">

**Comment by mcorner** [comment]
@andrewjmeier Thanks for the feedback, let me think about that.  18.0.0 (GA) was a big break from <18 (preview).  The preview and GA have entirely different APIS (and guts).  But glad you found this, we are big fans of making all of this findable on github. 

> Am I reading this correctly that App Attest is only needed for local development?
The entitlement yes, but AppAttest is used in prod and dev.

**Comment by jpeckner** [comment]
@mcorner I know it's been a little while here, but just wanted to double-check if this is still valid: is App Attest required for Recaptcha v18 to work in App Store builds?

**Comment by mcorner** [comment]
You don't have to do anything special for production.  The directions above are only needed if you care about the scores you see in development.

Or maybe I don't understand the question.

**Comment by jpeckner** [comment]
@mcorner Nope, that answered exactly what I was looking for; appreciate the quick response!
