### ISSUE TITLE
 Recaptcha.getClient(siteKey:) - returns error 4

### ISSUE THREAD

**Issue by dimitris-c** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#19]
**Describe the bug**

In regard to this issue #14 I've downloaded the latest version 18.0.3 and it now seems to be returning a different error.
Is this perhaps a configuration error, given that others are not getting this?

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [x] SPM
* [ ] Cocoapods
* [ ] Direct Download

**SDK Version (e.g. 18.0.1):**

18.0.3

Cannot retried recaptcha client from Recaptcha.getClient(siteKey:)

**Expected behavior**

Should be able to retrieve the client.

**Screenshots**

N/A

**Xcode version (please complete the following information):**
 - Version: Xcode 14.1

**Device (please complete the following information):**
 - Model: iPhone 14, iPhone 13.3, iPhone XS Max
 - OS: iOS 16, iOS 15.5
 - Simulator or real Device?  Both

**Additional context**

**Comment by mcorner** [comment]
Check that the bundle identifier in your app matches the one specified in your site key in the cloud console.

**Comment by dimitris-c** [comment]
thanks, this is just configuration issue

**Comment by mcorner** [comment]
For posterity: The errorMessage field will give this explanation.  We will update our sample code to include this.
