### ISSUE TITLE
Crach on getClient

### ISSUE THREAD

**Issue by SurglogsGithubUser** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#20]
**Crash on getClient**

**Integration Method**

* [ ] SPM

**SDK Version: 18.0.2**

**To Reproduce**

1. Call getClient on main thread :
```
init() {
        Recaptcha.getClient(siteKey: DefaultRecaptchaVerifier.id) { recaptchaClient, error in
            if let recaptchaClient {
                self.client = recaptchaClient
            }
            if let error = error {
                self.creationError = error
                print("RecaptchaClient creation error: \(error).")
                Logger.warning(error)
            }
        }
    }
```

**Expected behavior**
Return token without crashing

**Screenshots**
![Snímka obrazovky 2022-12-13 o 14 49 57](https://user-images.githubusercontent.com/107618883/207345531-f52e5923-18e2-465e-97cb-b10d9a5fd0a2.png)

![Snímka obrazovky 2022-12-13 o 14 38 46](https://user-images.githubusercontent.com/107618883/207345622-5851f93b-2b2a-4923-9371-b33e3571b5aa.png)

**Xcode version (please complete the following information):**
 - Version [e.g. Xcode 14.1]

**Device (please complete the following information):**
 - Simulator and also Real device, current iOS16.1

**Comment by SurglogsGithubUser** [comment]
Great, thank You, problem was that I had -Objc there, not -ObjC

**Comment by mcorner** [comment]
Note that -ObjC is no longer required as of 18.4.0
