### ISSUE TITLE
getClient fails with error code 100

### ISSUE THREAD

**Issue by bjjeong** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#23]
**getClient fails with error code 100**

We have been using SDK version 18.0.3 with no issues until today. However, we are suddenly getting errors when calling `getClient` with the following error: `Error code: 100`. I know that this has already been reported in https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/issues/14 but we are on the updated version and it has been working fine so far, so not sure what has suddenly changed.

Once I downgrade the SDK to 17.X.X, I am able to initialize again.

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [x] Cocoapods

**SDK Version (e.g. 18.0.1):**
- 18.0.3

**To Reproduce**

1. Call `getClient` to initialize the SDK

**Expected behavior**

- We expect to be able to initialize the SDK with no problems.

**Xcode version (please complete the following information):**
 - Version 14.2

**Device (please complete the following information):**
 - Model: iPhone (all)
 - OS: Various versions
 - Occurs on both simulator and real devices

**Comment by mcorner** [comment]
Yep, we noticed this an hour ago.  We are in the middle of a server rollout and have paused.  This will affect a portion of traffic until we track it down.  Thanks for the report.

**Comment by mcorner** [comment]
We identified the issue, it is almost entirely rolled back now.  Thanks for the report.

**Comment by bjjeong** [comment]
thanks @mcorner!
