### ISSUE TITLE
Are there reference docs for the iOS package?

### ISSUE THREAD

**Issue by niehusstaab** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#37]
My team is migrating back to recaptcha after a year or two away, and it seems like the library usage has changed a bit in the mean time (e.g. `getClient` is now an async function). I was looking around for reference documentation, but I haven't been able to find anything.

There is, of course, the quick start docs that are pointed to by all the internal recaptcha resources, but that doesn't really tell me about what situations could cause errors to be returned by the public functions: https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps
I did find reference docs for the mobile Android sdk, but there doesn't seem to be an accompanying one for iOS: https://cloud.google.com/recaptcha-enterprise/docs/apis

Particularly I was wondering about the meanings of the error codes that `getClient` returns. For example, "Error code: 2" is meaningless to me without docs. I can make a guess based on the Android SDK documentation `RecaptchaErrorCode` enum, but that assumes that the iOS enum is identical to, and has the same order as, the Android enum, which is not usually a safe assumption.

Sorry if this isn't the right place to ask!

**Comment by niehusstaab** [comment]
Looks like the error message for "Error code: 2" does correspond to the enum case from the Android docs; "Invalid Site Key".
I would still like to know if there are any available docs though so I don't have to guess and check as much.

**Comment by mcorner** [comment]
First quick thing: You want error.errorMessage not the code. This is in the integration docs.

**Comment by mcorner** [comment]
Other than that we don't yet have API docs for the SDK.  We are working on find an internal tool to generate them similar to Android.   I will close this for now as the original problem is fixed.
