### ISSUE TITLE
Android scores are always 0.7 SDK 18.1.1

### ISSUE THREAD

**Issue by serhiimore90** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#41]
Devices: real and simulators

SDK Version: 18.1.1
Google Maven repository
Autotest framework: Appium 

Steps to reproduce:
1. Run autotests with “custom_login” action;
2. Send “FRAUDULENT” annotation after 3 “send SMS OTP code” attempts in a row;
3. Send cURL "LEGITIMATE" annotation after each positive activation with entering valid SMS OTP code;
4. Check gCloud console metrics.

Actual result:
Scores are always 0.7 after more than 3k activations.

Expected result:
2nd step – score < 0.7;
3rd step – score >= 0.7.

cURL sent accordingly to: [Annotating an assessment](https://cloud.google.com/recaptcha-enterprise/docs/annotate-assessment ) 

Investigation:
We ran the same tests with SDK v. 18.0.3 and also got 0.7, also we have iOS implementation and scores are different: 0.3 for Fraudulent and 0.7 for Legitimate which means it works on iOS, but we didn’t get 0.9 on manual (human) login. For manual login results are the same.

**Comment by mcorner** [comment]
Unfortunately we are unable to provide support for scoring related questions in this forum, only integration questions.  In this case you will need to submit a cloud support request.
