### ISSUE TITLE
Recaptcha Error 100 after several hours of inactivity

### ISSUE THREAD

**Issue by Vitaliy-Sh** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#43]
**Describe the bug**

After a few hours the SDK starts sending error "The operation couldn’t be completed" (com.google.recaptcha error 100) when requesting a Recaptcha Token.
It doesn't matter if we use a new Recaptcha Client or the same one.
Nothing helps, only restarting the application.

**Integration Method**

* [x] SPM (iOS)
* [ ] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version (e.g. 18.0.1):**
18.1.2

**To Reproduce**

1. Initialise the client
2. Request a token (successful)
3. Minimize the application for a few hours
4. Open the application after that
5. Request token
6. Receive error
7. (Can repeat step 5 many times - the same result)

Creating a new Recaptcha Client doesn't help. The same error occurs.

**Expected behavior**

SDK should produce a Recaptcha token.

**Xcode version for iOS (please complete the following information):**
 - XCode 14.2 

**Device (please complete the following information):**
 - Model: iPhone 13 Pro Max
 - OS: iOS 16.1.2, 16.4.1
 - Real Device

**Comment by mcorner** [comment]
Yes, thanks for the report. We are aware of this particular big and have fixed it internally. We are validating it and expect to have it included in the next release (a few weeks probably).

**Comment by Vitaliy-Sh** [comment]
Thanks @mcorner! Is it possible to try this fix earlier? Because we have users that stuck with this problem. Also, we would like to try (test) this fix from our side too.

**Comment by mcorner** [comment]
Yes and no.  I wouldn't want you to put it into production as it makes version management on the backend complicated for us (and it will eventually bite you).  However, we would love it if you want to try out a prerelease version. Obviously it may or may not work, etc. Etc.  If so, drop me an email at my first name and my last name @google.com.

**Comment by andrewjmeier** [comment]
Hey @mcorner, following up here from the other issue thread from a month or so ago. Looks like some of the errors have gone down but we're seeing this issue as well. (I'll send you an email about testing out the prerelease version)

**Comment by mcorner** [comment]
Yes, just replied to the email. One other person is testing as well. Thanks for helping!

**Comment by ihnatmoisieiev** [comment]
@mcorner great! Looking forward to a quick release soon 😉

**Comment by mcorner** [comment]
Should be early this coming week.  18.2.0

**Comment by mcorner** [comment]
18.2.0 is out.  Release notes on the official page will follow, but draft release notes below. 

I am closing this bug for now, but please reopen it if you see the same behavior in 18.2.0

* The SDK is now built with Xcode 14
* Deprecated the existing API, which will be removed in the next major release. Added a new API that:
    - Returns a String instead of a RecaptchaToken in execute calls.
    - Adds a timeout parameter to both execute and getClient public APIs.
* Fixed a bug where the client would become unusable in some situations (https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/issues/43)
* Speculative fix for a rare crash (https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/issues/44)
* Added a new Interop Pod dependency in support of future Firebase integration.

**Comment by ihnatmoisieiev** [comment]
@mcorner unfortunately there are some issues while updating to 18.2.0 via SPM 😔
Could you please check it and fix it ASAP?
There are no such errors in 18.1.2.

<img width="977" alt="Screenshot 2023-05-02 at 07 34 53" src="https://user-images.githubusercontent.com/11294008/235587258-a3e0eba7-adab-40a2-9ae2-b187df2c7ec8.png">
<img width="947" alt="Screenshot 2023-05-02 at 07 35 01" src="https://user-images.githubusercontent.com/11294008/235587266-86e33bf3-d264-4e25-b2ae-49258eed92f9.png">
<img width="332" alt="Screenshot 2023-05-02 at 07 35 32" src="https://user-images.githubusercontent.com/11294008/235587280-4b9923cf-1458-4a36-b22d-7364896d5c77.png">

**Comment by mcorner** [comment]
@ihnatmoisieiev would you mind opening a new bug?  Thanks, we will figure this out today.
