### ISSUE TITLE
Firebase 10.0.0 GTMSessionFetcher

### ISSUE THREAD

**Issue by SurglogsGithubUser** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#5]
Hi,
there is a problem with FIrebase 10.0.0 and recaptcha.
Versions of GTMSessionFetcher are not compatible. 

Could you please update GTMSessionFetcher version to newer?

**Comment by mcorner** [comment]
GTMSessionFetcher has been removed as a dependency (along with many others) in v18.
