### ISSUE TITLE
SPM and direct downloading url are broken in 18.2.0

### ISSUE THREAD

**Issue by ihnatmoisieiev** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#51]
**Describe the bug**

SPM is not working in 18.2.0.
Also, I noticed that [Direct Download](https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps#prepare_your_environment) link from the docs is downloading 18.1.2 version instead of 18.2.0.

**reCAPTCHA Site Key**

No needed.

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [x] SPM (iOS)
* [ ] Cocoapods (iOS)
* [x] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version (e.g. 18.0.1):**
18.2.0

**To Reproduce**

1. Install or update v18.2.0 via SPM
2. Errors occur:
<img width="332" alt="Screenshot 2023-05-02 at 07 35 32" src="https://user-images.githubusercontent.com/11294008/235848553-3304c3d7-aebd-4afe-87c7-1d6d17c5cd89.png">
<img width="947" alt="Screenshot 2023-05-02 at 07 35 01" src="https://user-images.githubusercontent.com/11294008/235848559-db94941b-7491-4e1a-bdad-39c6c676ada6.png">
<img width="977" alt="Screenshot 2023-05-02 at 07 34 53" src="https://user-images.githubusercontent.com/11294008/235848563-3c9f00bc-826b-44cb-a60f-40850fb9d77f.png">

1. Go to docs [link](https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps#prepare_your_environment)
2. Select "Direct Download"
4. Press on "client"
5. 18.1.2 is downloading instead of 18.2.0.

The current url looks like:
```
https://dl.google.com/recaptchaenterprise/v18.1.2/RecaptchaEnterprise_iOS_xcframework/recaptcha-xcframework.xcframework.zip
```

**Expected behavior**

1. SPM works with 18.2.0 without issues.
2. [Direct Download](https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps#prepare_your_environment) link is downloading the latest release version 18.2.0.

**Xcode version for iOS (please complete the following information):**
 - Xcode 14.3

**Device (please complete the following information):**
No needed

**Additional context**
No needed

**Comment by mcorner** [comment]
The direct download link has not been released yet (it always lags the spm and pod release)

We put out a fix for spm last night, but it is the same version so please try clearing your spm crash and try again.  

Thanks!

**Comment by ihnatmoisieiev** [comment]
@mcorner SPM is fixed, the direct download link is still 18.1.2.

**Comment by mcorner** [comment]
yes, there is a delay in getting the documentation improved.  Here is a link in the meantime: https://dl.google.com/recaptchaenterprise/v18.2.0/RecaptchaEnterprise_iOS_xcframework/recaptcha-xcframework.xcframework.zip

**Comment by mcorner** [comment]
This was fixed a while ago, forgot to close.
