### ISSUE TITLE
Using reCaptcha in older devices that switch between storyboards

### ISSUE THREAD

**Issue by walterjgsp** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#53]
**Describe the bug**

Using reCaptcha in older devices that switch between storyboards return internal exception in calling execute a second time.

**reCAPTCHA Site Key**

Please include your site key so we can examine backend metrics for your integration.

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [ ] SPM (iOS)
* [X] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version (e.g. 18.0.1):** 18.2.0

**To Reproduce**

Use reCaptcha in a real device with old iOS (iOS 13-) that switch between storyboards and call execute, in the second time it will fail with an internal error.

**Expected behavior**

Should execute and return a token.

**Xcode version for iOS (please complete the following information):**
 - Version 14.2

**Device (please complete the following information):**
- iPhone 8, iOS 13.2
- iPhone 6, iOS 12.7

**Comment by mcorner** [comment]
We have been able to reproduce and fix this bug and this will be in the next release of the iOS SDK (likely 18.2.1)

**Comment by mcorner** [comment]
This was fixed in 18.2.1.
