### ISSUE TITLE
PlatformException

### ISSUE THREAD

**Issue by MrVipinVijayan** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#56]
PlatformExceptiion while doing initClient

Caught exception on execute: PlatformException(FL_EXECUTE_FAILED, Initialize client first, null, null)

6Lez6tImAAAAAHeKgT2T90MpEJjvAU-hVfqWwQPm

Added package in pubspec.yaml

**Comment by mcorner** [comment]
Thia appears to be related to flutter. Please file here: https://github.com/GoogleCloudPlatform/recaptcha-enterprise-flutter
