### ISSUE TITLE
grecaptcha.execute(widgetId, {action: true}); in v3 doesn't return response if the action is "true"

### ISSUE THREAD

**Issue by esSoftPalinaTsi** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#58]
**Describe the bug**

**reCAPTCHA Site Key** 
SIte Key is 6LfNILslAAAAAE-LUCDY6vkjRELK0oA4Ai1Fj5HV

1. Go to captcha protected form
2. Click on submit
3. If I call grecaptcha.execute(widgetId, {action: true}); no token is generated

**Expected behavior**

grecaptcha generates the token

**Screenshots**

**Device (please complete the following information):**
 - Firefox, Chrome

**Comment by mcorner** [comment]
This is the web version of recaptcha, not the mobile SDK.  Please contact
