### ISSUE TITLE
[Bug]: iOS Mobile SDK with versions above 18.0.3 (18.1.0+) doesn't not work.

### ISSUE THREAD

**Issue by mikehouse** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#62]
### Are you seeing the problem on Android or iOS?

iOS

### Contact Details

GitHub account

### Describe the bug

Moving from 18.0.2 to 18.2.2 does not work

### Select the method used to integrate with reCAPTCHA Mobile.

Cocoapods (iOS)

### SDK Version

18.2.2

### To Reproduce

I updated Podfile to use new version of SDK from 18.0.2 to 18.2.2 and it does not work. I tried all other versions 18.1.0-18.2.2 and no one was working, only 18.0.3 and below are okay.

To be honest I do not remember how the SDK was first time integrated in an app, I just reviewed SDK integration guide (https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps) and see there info about App Attest

```
reCAPTCHA Enterprise uses Apple's AppAttest as part of its detection engine. 
If you don't plan to use a testing key with a fixed score for local development, do the following:

In Xcode, add the App Attest capability to your app.
In your project's .entitlements file, set the App Attest environment to production.
```

I didn't do it (adding the App Attest capability), can it be a reason that SDKs > 18.0.3 do not work ?
Thanks in advance.

### Expected behavior

Update SDK should work

### Development IDE

Xcode 14.3.1

### To Reproduce

- Model: [all]
- OS: [16.5.1]
- real Device (TestFlight builds)

**Comment by mcorner** [comment]
Can you be more specific on "does not work"?  Does not complile?  Throws an error, etc?

**Comment by mikehouse** [comment]
Hello. Backend guys say that they cannot pass validation with the data from mobile application, as I understand it says that the mobile app is a bot. After that I just downgraded the SDK version to 18.0.3 (initial version was 18.0.2) from 18.2.2 and ran the application again, then all started to work. I will try to ask the backend for more info. Thank you 🙂

**Comment by mcorner** [comment]
Without more a more specific bug report, I have to close this issue.
