### ISSUE TITLE
error log :  Key type invalid 

### ISSUE THREAD

**Issue by aBenVip** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#64]
**Describe the bug**

error log  Key type invalid ,this issue  when init recaptcha andorid sdk

**reCAPTCHA Site Key**

6LdC7jInAAAAAGsO78e1PiMPMBzSKoewAe7dl00d

Please include your site key so we can examine backend metrics for your integration.

**Integration Method**

andorid mobile sdk

Select the method used to integrate with reCAPTCHA Mobile.

* [ ] SPM (iOS)
* [ ] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version (e.g. 18.0.1):**

**To Reproduce**

execute  Recaptcha.getClient(application, reCaptchaKey) method 

**Expected behavior**

**Screenshots**

**Xcode version for iOS (please complete the following information):**
 - Version [e.g. Xcode 13.4.1]

**Device (please complete the following information):**
 - Model: [e.g. Pixel 7, iPhone6]
 - OS: [e.g. Android 28, iOS8.1]
 - Emulator/Simulator or real Device? 

   HUAWEI NAM-AL00

   harmonyOS 3.0.0
**Additional context**

**Comment by mcorner** [comment]
You need to enable the key for use on devices lacking Google play services in the console.
