### ISSUE TITLE
Result score is always 0.3

### ISSUE THREAD

**Issue by MichaelBabets** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#65]
Hey, I always get a score = 0.3, when I try to do login on emulators, real devices, or through automated tests.

I'm using the last version of the package, flutter v.3.7.11, VPN for connecting to the server.

I want to prevent from bots being able to log in. So at the start of the app, I run the `initClient()` method. 
When the user put credentials I call `execute(RecaptchaAction.LOGIN())`, and the score in the token is always 0.3 whatever I do.

How does the captcha calculate the score and what can I do to increase the value?

**Comment by mcorner** [comment]
We cannot provide specific scoring support in this forum, but in general testing environments will not match what you see in production.  Our best practice is to put it into production behind a feature flag, take no actions based on the score, and monitor the scoring behavior.
