### ISSUE TITLE
iOS App crashes when ReCaptcha Client is requested with site key

### ISSUE THREAD

**Issue by nik6018** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#68]
**Describe the bug**

Running the App with ReCaptcha Enterprise SDK on iOS is causing a crash when ReCaptcha Client is requested.

```
2023-08-23 19:28:39.506442+0530 ReCaptchaSDKTest[1906:189843] -[RCAx_GPBTimestamp initWithTimeIntervalSince1970:]: unrecognized selector sent to instance 0x2817c28e0
2023-08-23 19:28:39.507163+0530 ReCaptchaSDKTest[1906:189843] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCAx_GPBTimestamp initWithTimeIntervalSince1970:]: unrecognized selector sent to instance 0x2817c28e0'
*** First throw call stack:
(0x195f17180 0x1950ef9f8 0x195e339bc 0x195f1c9c8 0x195f1e65c 0x100b6a0cc 0x100b46f48 0x100b46ffc 0x100b35be4 0x1010476f4 0x101048c78 0x101050bf4 0x1010518b4 0x10105b77c 0x195b36114 0x195b38cd4)
```

**reCAPTCHA Site Key**

`6LfoL8snAAAAAMjTYmFPsbT0uuuQAoyuwZA4SbFI`

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [x] SPM (iOS)
* [ ] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version (e.g. 18.0.1):**

18.3.0

**To Reproduce**

1. Configure the SDK into the app using the instructions given at : [link](https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps)
2. Run the app on device
3. Once code for Client generation is executed
4. App crashes with the above mentioned error

**Expected behavior**

ReCaptcha Client should be generated without any crash of the app

**Screenshots**

- Screenshot when the app crashes
https://paste.pics/c798ba494ed1f931ad5f667d9be48fd4

**Xcode version for iOS (please complete the following information):**
 - 14.3.1

**Device (please complete the following information):**
 - Model: [iPhone6]
 - OS: [iOS 12.5.7]
 -  Real Device 

**Additional context**

A user faced similar issue on StackOverFlow, he forgot to configure the Objc Bridging Header file, after configuring the same his issue was resolved.
[SO Link](https://stackoverflow.com/questions/76012635/while-initialising-recaptcha-enterprise-in-ios-app-im-getting-unrecognized-sele)

In my case I have configured everything correctly and followed the step by step instructions but still the App crashes when it tries to get a Client using the site key

I have a .zip file of my project uploaded on drive, which you can download and check if you have Xcode 14
https://drive.google.com/file/d/1YE99gkBv5bfxjzFAkl6IbU24KGJfbGho/view?usp=sharing

**Comment by mcorner** [comment]
-ObjC not -Objc

Common mistake!
