### ISSUE TITLE
 pod update I get this warning.

### ISSUE THREAD

**Issue by DeokHo98** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#69]
### When I start pod update I get this warning.

![스크린샷 2023-08-29 오전 9 48 15](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/93653997/71e9d3f0-3823-40e5-9657-88ccf1ab88f1)

### When I click on the link, I get this warning
![스크린샷 2023-08-29 오전 9 48 34](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/93653997/0ca95334-5537-4b15-948d-90f234b4dad6)

Google console IAM jeongdeokho98@gmail.com The email is properly registered.
I haven't been able to update my pod for days

### my Podfile

```

# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://cpdc-eap.googlesource.com/RecaptchaEnterprise.git'

target 'myApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for myApp
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxKeyboard'
    pod 'RxDataSources'
    pod 'RxViewController'
    pod 'Alamofire'
    pod 'Firebase/Core'
    pod 'Firebase/Analytics'
    pod 'Firebase/Messaging'
    pod 'Firebase/Auth'
    pod 'Firebase/Crashlytics'

  # Google reCAPTCHA Enterprise
    pod 'RecaptchaEnterprise'
  
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        end
      end
    end
    
  target 'myAppTest' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'myAppUITest' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

**Comment by mcorner** [comment]
Thanks for this report.  This is definitely something on our end (we recently changed how we are importing a dependency and something is wrong here).  We will get back to you ASAP

**Comment by mcorner** [comment]
@DeokHo98 Why do you have this line in your pod?

`source 'https://cpdc-eap.googlesource.com/RecaptchaEnterprise.git'`

This isn't needed (https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps?hl=es-419#cocoapods)

But I am wondering where you copied that from?

Pods are distributed through the public

**Comment by DeokHo98** [comment]
@mcorner 
thank you for your answer
```
source 'https://cpdc-eap.googlesource.com/RecaptchaEnterprise.git'
```
this is in the reCAPTCHA Enterprise documentation in Korean.
https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps-preview?hl=ko
![스크린샷 2023-08-30 오전 8 14 06](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/93653997/2494fb5c-007b-4d77-8063-656281ceef02)

**Comment by DeokHo98** [comment]
thank you I will decide after discussing it with my co-workers :)
