### ISSUE TITLE
cesdb database not exist exception

### ISSUE THREAD

**Issue by aBenVip** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#73]
**Describe the bug**

**reCAPTCHA Site Key**

6LdSZEwnAAAAAFvuD4TweCPpX0mMn5bhLx66ZxU9

**Integration Method**

Recaptcha.getClient()

Device: Android 

**SDK Version (e.g. 18.0.1):**

**To Reproduce**

**Expected behavior**

init recaptcha android sdk

**Screenshots**

![截屏2023-09-25 11 24 20](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/24616560/9d9a63a8-4416-43a6-8359-a1cd541c2393)

**Device (please complete the following information):**
![截屏2023-09-25 11 24 26](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/24616560/4434edce-4b47-4b05-b00f-c10c107cbf15)

**Additional context**

**Comment by mcorner** [comment]
Thanks for the bug report.  We have identified where this can happen, I would guess this device is out of disk space or something else that prevents us from writing files.  We will add something to handle this in the next release of the SDK.

Thanks!

**Comment by aBenVip** [comment]
I also think so. How can I catch this crash before you release a new version?
I added try-catch code when initializing the sdk, but did not catch this exception

**Comment by mcorner** [comment]
Unfortunately, you can't catch it as it is in a background thread.

If my theory about disk space is correct, you could check free disk space before initializing the SDK.  I imagine this user/device would be having other problems if this were the case.

We will have a fix in the next release of course.

**Comment by aBenVip** [comment]
![截屏2023-09-27 10 14 50](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/24616560/2d55aa9b-9c7e-420c-bcaf-0c346a510637)
Maybe it's not a disk space issue,

**Comment by mcorner** [comment]
Perhaps not, but something is preventing writes.  How many devices are you seeing this on?

**Comment by aBenVip** [comment]
![截屏2023-10-07 10 32 41](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/24616560/b85f0c5c-9dbc-4bd8-b693-175931f5945e)

**Comment by aBenVip** [comment]
All are transsion devices, and android12

**Comment by mcorner** [comment]
This was fixed in v18.4.0. Let us know if you run into it again.
