### ISSUE TITLE
Recaptcha crash on initialize

### ISSUE THREAD

**Issue by hasanilyas185** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#87]
**Describe the bug**

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(FL_INIT_FAILED, com.google.android.recaptcha.RecaptchaException: Internal Error, null, null). Error thrown PlatformException(FL_INIT_FAILED, com.google.android.recaptcha.RecaptchaException: Internal Error, null, null).
StandardMethodCodec.decodeEnvelope (message_codecs.dart:652)
MethodChannel._invokeMethod (platform_channel.dart:310)
MethodChannelRecaptchaEnterprise.initClient (recaptcha_enterprise_method_channel.dart:34)
RecaptchaEnterpriseService.initClient (recaptcha_enterprise.dart:14)

**reCAPTCHA Site Key**

Please include your site key so we can examine backend metrics for your integration.

**Integration Method**

Flutter pub cache dependency

**SDK Version (e.g. 18.0.1):**
18.4.0

**To Reproduce**

cannot reproduce on our development environment but we can see 422 crash in 2 days on firebase crashlytics 

We cannot reproduce the issue, during our development and testing.

**Expected behavior**

**Screenshots**
<img width="1549" alt="Screenshot 2024-02-07 at 10 44 33 AM" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/44157654/9d24dff9-2b7d-4990-a942-598864a696ce">

**Xcode version for iOS (please complete the following information):**
 - Xcode 15.0

**Device (please complete the following information):**
 - Model: [e.g. Pixel 7, iPhone6]
 - OS: [e.g. Android 28, iOS8.1]
 - Emulator/Simulator or real Device? 

**Additional context**

**Comment by walterjgsp** [comment]
Hi @hasanilyas185. Thanks for the report! 

From the screenshot it appears you're encountering network exceptions. Have you implemented retries in your code? Our past experience suggests that retry mechanisms greatly help, even when dealing with internal errors.

**Comment by hasanilyas185** [comment]
Hi @walterjgsp i have implemented retry in my code but still facing the same issue

**Comment by romaCaldeira** [comment]
I have the same problem

**Comment by walterjgsp** [comment]
Hi @romaCaldeira, it's also Flutter or is native iOS or Android? What's the version of the SDK that you're using? Have you implemented retries in your code?

**Comment by walterjgsp** [comment]
Thanks @romaCaldeira, in what platform does the exceptions happen more often? Android or iOS? Do you know the current ratio of these errors?

**Comment by romaCaldeira** [comment]
@walterjgsp happens a lot on both IOS and Android

number of errors in the last 7 days

IOS 
![Captura de Tela 2024-02-22 às 10 51 48](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/19198962/abb0f609-674e-4a67-854b-f16b42661e02)

Android
![image](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/19198962/2e39e30e-017c-475a-ad47-169df0d84815)

**Comment by romaCaldeira** [comment]
and specifically in the IOS 17.3.1 version, when PlatformException(1, Network Error., null, null) occurs, the app freezes and it is necessary to reinstall the application.

**Comment by walterjgsp** [comment]
Thanks for the answers @romaCaldeira! We plan to release Flutter versions 18.4.2 and 18.5.0-beta01, which should improve those metrics. I'll update this issue when available."

**Comment by romaCaldeira** [comment]
@walterjgsp 
I will have an idea of a deadline, so we can organize ourselves here and pass the feedback on to our users.

**Comment by walterjgsp** [comment]
Hi @romaCaldeira would you mind send filling [recaptcha-mobile-github](https://forms.gle/sThtVbNBwPh2kVfb9) with your site key so we can investigate further?

**Comment by romaCaldeira** [comment]
@walterjgsp 

Permission required
This form can only be viewed by users in the owner's organization.

Please contact the form owner if you think this is an error. [Know more](https://support.google.com/docs/?p=forms_settings) .

![image](https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/19198962/8d6d3758-5aa3-439c-8556-37dbce9b7e2f)

**Comment by walterjgsp** [comment]
@romaCaldeira, please try the form again. https://forms.gle/2xxpZbgqCvNgvDHDA

**Comment by romaCaldeira** [comment]
@walterjgsp sent IOS key and Android key

**Comment by walterjgsp** [comment]
@romaCaldeira thanks for the site keys. We're on it – investigating the issue and exploring SDK improvements.

**Comment by hasanilyas185** [comment]
I've seen that your new version, 18.4.2, has been released on pub.dev. Could you please confirm if these issues have been resolved in that version?

**Comment by walterjgsp** [comment]
@hasanilyas185, the version 18.4.2 was to tackle the issues https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/issues/89, https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/issues/88 and https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/issues/90. 

We've begun addressing the issues you're facing in version 18.5.0 (Beta01) of the SDK. Flutter doesn't have beta SDK releases, we're actively working to finalize a stable version. 

To help us troubleshoot, are you able to provide the percentage of requests that result in exceptions (e.g., 10%, 4%)? It's also important to remember that some level of network errors is expected due to environmental factors.

**Comment by hasanilyas185** [comment]
Thank you for the update. Currently, we are not monitoring requests, which makes it challenging to provide a precise percentage of progress. However, we are looking forward to the release of the new beta version. Please keep us informed once it is available.

**Comment by walterjgsp** [comment]
@romaCaldeira, I'm fine, thanks for asking and how about you? 

> Do you know when we will have the test version on Flutter?

We're currently in discussion about potentially adopting beta versions for our Flutter wrappers. Our initial policy was to limit both React Native and Flutter wrappers to stable releases. I'll keep you informed as the situation develops.

**Comment by romaCaldeira** [comment]
@walterjgsp 
I'm fine, I'm just looking forward to the solution, I'm waiting, thank you very much.

**Comment by romaCaldeira** [comment]
@walterjgsp 
all good?
We already have some feedback on this issue, do we have a date for a Flutter version?

**Comment by walterjgsp** [comment]
Hi @romaCaldeira, we're planning a new iOS and Android beta release next week. I'm advocating for a simultaneous Flutter beta release and will keep you posted on the decision.

**Comment by romaCaldeira** [comment]
@walterjgsp 
ok, I'll wait, thank you very much

**Comment by hasanilyas185** [comment]
Hello @walterjgsp any update about the flutter version release?

**Comment by walterjgsp** [comment]
@romaCaldeira and @hasanilyas185. Flutter 18.5.0-beta02 is now available! Please test it out and provide feedback. Note: This is a beta-release version, so some features may change before the stable release.

**Comment by romaCaldeira** [comment]
@walterjgsp 
How wonderful, let's test it here, we'll provide feedback soon

**Comment by hasanilyas185** [comment]
@walterjgsp thanks for the update will test and provide feedback soon

**Comment by mcorner** [comment]
Also see #100

**Comment by hasanilyas185** [comment]
@walterjgsp  on version 18.5.0-beta02 facing this crash on iphone X and iOS emulator of iphone X app is crashing instantly and when removing the package it is working fine


Incident Identifier: D63995C3-054C-471F-9E21-746391CD06A7
CrashReporter Key:   4FD3ADA0-7908-C6CA-B0E9-C5E487B7E026
Hardware Model:      MacBookPro16,1
Process:             Runner [8053]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/ED232CF9-202B-4955-8885-4F4D6ADB6AB8/data/Containers/Bundle/Application/66D10A04-8EB4-4587-8436-1C6D8A5C9378/Runner.app/Runner
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [3964]
Coalition:           com.apple.CoreSimulator.SimDevice.ED232CF9-202B-4955-8885-4F4D6ADB6AB8 [1672]
Responsible Process: SimulatorTrampoline [1457]
Date/Time:           2024-04-08 08:55:02.4726 +0500
Launch Time:         2024-04-08 08:55:02.0145 +0500
OS Version:          macOS 14.4.1 (23E224)
Release Type:        User
Report Version:      104
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: DYLD 4 Symbol missing
Symbol not found: _$s7Network13NWPathMonitorCMn
Referenced from: <A43A783E-FA68-3B1F-A698-3FE503B19D07> /Users/USER/Library/Developer/CoreSimulator/Devices/ED232CF9-202B-4955-8885-4F4D6ADB6AB8/data/Containers/Bundle/Application/66D10A04-8EB4-4587-8436-1C6D8A5C9378/Runner.app/Runner
Expected in:     <4FBD92F7-FFB6-36E1-944F-0D3C78779AC3> /Volumes/VOLUME/*/Network.framework/Network
(terminated at launch; ignore backtrace)
Triggered by Thread:  0
Thread 0 Crashed:
0   dyld                          	       0x11014db3e __abort_with_payload + 10
1   dyld                          	       0x110166bb7 abort_with_payload_wrapper_internal + 82
2   dyld                          	       0x110166be9 abort_with_payload + 9
3   dyld_sim                      	       0x107495829 abort_with_payload + 26
4   dyld_sim                      	       0x107440fea dyld4::halt(char const*) + 375
5   dyld_sim                      	       0x10743f535 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3953
6   dyld_sim                      	       0x10743e25f _dyld_sim_prepare + 577
7   dyld                          	       0x1100f0e47 dyld4::prepareSim(dyld4::RuntimeState&, char const*) + 1558
8   dyld                          	       0x1100ef5f6 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 279
9   dyld                          	       0x1100e

**Comment by mcorner** [comment]
Can you confirm the minimum iOS version set in your project and the version of xCode?

**Comment by hasanilyas185** [comment]
My Xcode version is 15.0, and the minimum deployment target is currently set to iOS 11. I'll update this setting and then provide feedback soon.

**Comment by walterjgsp** [comment]
To give you a little more context @hasanilyas185 this happens because Xcode 15 dropped iOS 11 SDK as can be seen here: 
https://developer.apple.com/support/xcode/ 

So for some reason when you place the minimum iOS version as iOS 11 it will drop the deployment target and the frameworks symbols that are marked as 12 or greater will also be dropped. https://github.com/DataDog/dd-sdk-ios/issues/1509

**Comment by hasanilyas185** [comment]
okay thanks for the context @walterjgsp will update accordingly

**Comment by mcorner** [comment]
Unfortunately this issue became a mixture of several issues. 

We will eventually move network retries inside the sdk as part of #100 

Internal errors have been almost totally eliminated in 18.5.0-beta02 (and the rest in beta03 for iOS and a few remaining ones in Android will be eliminated in Android beta03). So closing this for now in favor of more focused issues.
