### ISSUE TITLE
The token authentication fails. Procedure

### ISSUE THREAD

**Issue by wiyun0518** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#93]
**Describe the bug**

**reCAPTCHA Site Key**

Please include your site key so we can examine backend metrics for your integration.

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [ ] SPM (iOS)
* [x] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version (e.g. 18.0.1):**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Xcode version for iOS (please complete the following information):**
 - Version [e.g. Xcode 13.4.1]

**Device (please complete the following information):**
 - Model: [e.g. Pixel 7, iPhone6]
 - OS: [e.g. Android 28, iOS8.1]
 - Emulator/Simulator or real Device? 

**Additional context**

**Comment by wiyun0518** [comment]
Describe the bug：
When I used the token obtained by the new 18.4.1 or 18.4.1 SDK to send it to the server for verification, the prompt code =1003 failed the verification, but I could verify and log in normally with the online package, but the online package used 17.0.0 and could not be downloaded

reCAPTCHA Site Key：6LcU36YgAAAAAIoNRJQz_aM7BUKXYPH4oD9qqapU

SDK Version：Version 18.0.0 or later

To Reproduce：
When I click on the login verification token

Screenshots：
<img width="826" alt="1" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/25146665/300a5a44-55c8-42a3-bb56-7aafe4859c9a">

 [Recaptcha getClientWithSiteKey:reCAPTCHA_KEY
                         completion:^void(RecaptchaClient* recaptchaClient, NSError* error) {
        if (!recaptchaClient) {
            dispatch_async(dispatch_get_main_queue(), ^{
                [vc.navigationController.view removeBlankView];
              DebugLog (@"%@", (RecaptchaError *)error.userInfo);

            });
            return;
        }
        [recaptchaClient execute:RecaptchaAction.login
            completion:^void(NSString* _Nullable  token, NSError* _Nullable error) {
          if (!token) {
              dispatch_async(dispatch_get_main_queue(), ^{
                  [vc.navigationController.view removeBlankView];
                DebugLog (@"%@", (RecaptchaError *)error.userInfo);

              });
            return;
          }
            
            NSDictionary *dic = [self requestLoginParams:account pwd:pwd token:token];

            [I_NetRequest requestWithHeader:nil path:AccountLoginURL params:dic methodType:YYRequestMethodPOST andBlock:^(id data, NSError *error) {
                [self clearWebviewCookie];
                
                if (!error) {     

**The above is the process of obtaining token and verification. The token is obtained, and the error code returned is 1003. The server colleague checked the reason that the token did not pass the verification on the Google side**

Xcode version for iOS：
Version 15.1 (15C65)    ,and the computer system is M1

Device: iPhone 12 Pro Max
System: 16.6.      iPhone 14 System 16.2， iPhone X  System 16.7.5，


Online version (17.0.0) can login to the same device within 10 times, but I can't log in to verify the token locally. The local environment and online environment are the same, only the version number is different, but online version 17.0.0, cocoaPods can't download anymore. pod search can only find version 18.0.0 or above.

**Comment by walterjgsp** [comment]
Thanks for the issue @wiyun0518. This isn't the right place for this kind of support. Please reach out to Google Cloud support at https://cloud.google.com/support.

**Comment by wiyun0518** [comment]
Ok, how can I download the RecaptchaEnterprise17.7.0 version?

**Comment by wiyun0518** [comment]
<img width="566" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/25146665/e40b7c3f-94d7-469a-af54-2fcac51fb609">
