### ISSUE TITLE
RecaptchaEnterprise 17.0.0 Download problem

### ISSUE THREAD

**Issue by wiyun0518** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#94]
**Describe the bug**
I see tag17.0.0 but I use cocoaPods pod search RecaptchaEnterprise as shown in the screenshot below
<img width="669" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/25146665/e7dc7720-d222-4767-8433-d8f2f953b182">

**reCAPTCHA Site Key**

Please include your site key so we can examine backend metrics for your integration.

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [ ] SPM (iOS)
* [x] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version (e.g. 18.0.1):**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Xcode version for iOS (please complete the following information):**
 - Version [e.g. Xcode 13.4.1]

**Device (please complete the following information):**
 - Model: [e.g. Pixel 7, iPhone6]
 - OS: [e.g. Android 28, iOS8.1]
 - Emulator/Simulator or real Device? 

**Additional context**
Since most of the tokens I obtained using the version after 18.0.0 failed to pass the verification, I would like to try the version 17.0.0 (it is normal for our online APP to use the version 17.0.0). But I can't download it right now

**Comment by mcorner** [comment]
Can you tell us what "failed to pass the verification" means?  You are getting an error from create assessment on your server?  What error are you getting?

17 is an old version of our SDK that was only downloadable via an allowlist.  Was someone in your org whitelisted to use it?

**Comment by wiyun0518** [comment]
Thank you very much for your reply. It is like this. The online version of our project uses 17.0.0, which allows normal login verification token. However, I cannot download 17.0.0 now, so I can only use the version after 18, but since February 7, these versions cannot normally verify the token with Google server. The back-end colleague told me that it was because my device environment score was relatively low, the score was generally 0.1 to 0.4, but the online version was normal, and the pass score we set was 0.6. Since several devices have such problems, and the devices themselves and the network have no problems, I don't know how to solve it now. I hope you can give me some suggestions, thank you.

Our online version using 17.0.0 is normal

**Comment by mcorner** [comment]
Ok, so you have two problems: accessing 17 and getting low scores in development. 

For 17, please try regenerating the gitcookie here: https://www.googlesource.com/new-password.  Then try to clone the git repo manually. If that doesn't work, I will need to know what email address you are using for it to make sure you are on the allowlist. 

For 18, you may have missed step 3 here for appattest: https://cloud.google.com/recaptcha-enterprise/docs/instrument-ios-apps#integrate_app

But overall scoring in development may not match what you will see in production.

**Comment by wiyun0518** [comment]
Thank you very much for your reply.
For 17：Do I need to execute the following command on my Mac terminal？
<img width="1181" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/25146665/8273a4a0-48b9-4b8e-b4a7-5def90736481">
For 18,
I saw that step 3 is the operation of reCAPTCHA Key, but I already have the reCAPTCHA Site Key, and this key is still the key from my original version 17.0. It is just that the token and server verification score I get now using the version after 18 is very low，as shown in the following screenshot, in many devices have a very low score
<img width="998" alt="image" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/25146665/c17530af-dd99-4c24-b7cd-b50cc873efdc">

**Comment by wiyun0518** [comment]
My code is as follows:
<img width="826" alt="1" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/25146665/aff71334-80df-4dee-8ede-2dcc958c0bf4">
Our server first got the token to verify with Google's server, and then continued to execute our own login if the verification passed, and now the verification token failed because "UNEXPECTED_ENVIRONMENT" .

**Comment by mcorner** [comment]
Make sure you are doing this part of the integration: 

reCAPTCHA Enterprise uses [Apple's AppAttest](https://developer.apple.com/documentation/devicecheck/establishing_your_app_s_integrity) as part of its detection engine. If you don't plan to use a testing key with a fixed score for local development, do the following:

In Xcode, add the App Attest capability to your app.

In your project's .entitlements file, set the App Attest environment to production.

**Comment by mcorner** [comment]
The detection (and scores) in v18 are completely different from v17.  I cannot comment here on scoring related issues, but what scores you get in development will not be the same as you get in production.  You should deploy v18 to production, monitor the scores and then make decisions based on that.

As for the cookie, that is the correct command, but you are using your personal email address.  v17 was a private preview and was only allowlisted for specific email addresses.  Please work through your sales/Client Engineering contacts or cloud support to address that.
