### ISSUE TITLE
Archive failed (symbol(s) not found for architecture arm64)

### ISSUE THREAD

**Issue by mrchauhan2802** [GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk#96]
Archive failed on one of the schemes 

**reCAPTCHA Site Key**

**Integration Method**

Select the method used to integrate with reCAPTCHA Mobile.

* [ ] SPM (iOS)
* [✅ ] Cocoapods (iOS)
* [ ] Direct Download (iOS)
* [ ] GMaven (Android)

**SDK Version (e.g. 18.4.1):**

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="803" alt="Screenshot 2024-03-07 at 3 10 37 pm" src="https://github.com/GoogleCloudPlatform/recaptcha-enterprise-mobile-sdk/assets/39663213/e69970f3-e066-44d8-b3d3-8ca5f70a67a0">

**Xcode version for iOS (please complete the following information):**
 - Version [e.g. Xcode 14.1]

**Device (please complete the following information):**
 - Model: [e.g. Pixel 7, iPhone6]
 - OS: [e.g. Android 28, iOS8.1]
 - Emulator/Simulator or real Device? 

**Additional context**

**Comment by walterjgsp** [comment]
Thanks for the report @mrchauhan2802. Just for context, what's the version of the SDK that you're trying to use and what Xcode version is being used to build the app?
